// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_character_updates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftCharacterUpdate = `-- name: CreateDraftCharacterUpdate :one
INSERT INTO action_result_character_updates (
    action_result_id,
    character_id,
    module_type,
    field_name,
    field_value,
    field_type,
    operation
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (action_result_id, character_id, module_type, field_name)
DO UPDATE SET
    field_value = EXCLUDED.field_value,
    field_type = EXCLUDED.field_type,
    operation = EXCLUDED.operation,
    updated_at = NOW()
RETURNING id, action_result_id, character_id, module_type, field_name, field_value, field_type, operation, created_at, updated_at
`

type CreateDraftCharacterUpdateParams struct {
	ActionResultID int32       `json:"action_result_id"`
	CharacterID    int32       `json:"character_id"`
	ModuleType     string      `json:"module_type"`
	FieldName      string      `json:"field_name"`
	FieldValue     pgtype.Text `json:"field_value"`
	FieldType      string      `json:"field_type"`
	Operation      string      `json:"operation"`
}

// Create or update a draft character update (upsert behavior on conflict)
func (q *Queries) CreateDraftCharacterUpdate(ctx context.Context, arg CreateDraftCharacterUpdateParams) (ActionResultCharacterUpdate, error) {
	row := q.db.QueryRow(ctx, createDraftCharacterUpdate,
		arg.ActionResultID,
		arg.CharacterID,
		arg.ModuleType,
		arg.FieldName,
		arg.FieldValue,
		arg.FieldType,
		arg.Operation,
	)
	var i ActionResultCharacterUpdate
	err := row.Scan(
		&i.ID,
		&i.ActionResultID,
		&i.CharacterID,
		&i.ModuleType,
		&i.FieldName,
		&i.FieldValue,
		&i.FieldType,
		&i.Operation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftCharacterUpdate = `-- name: DeleteDraftCharacterUpdate :exec
DELETE FROM action_result_character_updates
WHERE id = $1
`

// Delete a draft character update by ID
func (q *Queries) DeleteDraftCharacterUpdate(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDraftCharacterUpdate, id)
	return err
}

const deletePublishedDrafts = `-- name: DeletePublishedDrafts :exec
DELETE FROM action_result_character_updates
WHERE action_result_id = $1
`

// Delete all draft updates for an action result (called after publishing)
func (q *Queries) DeletePublishedDrafts(ctx context.Context, actionResultID int32) error {
	_, err := q.db.Exec(ctx, deletePublishedDrafts, actionResultID)
	return err
}

const getDraftCharacterUpdate = `-- name: GetDraftCharacterUpdate :one
SELECT id, action_result_id, character_id, module_type, field_name, field_value, field_type, operation, created_at, updated_at FROM action_result_character_updates
WHERE id = $1
`

// Get a single draft character update by ID
func (q *Queries) GetDraftCharacterUpdate(ctx context.Context, id int32) (ActionResultCharacterUpdate, error) {
	row := q.db.QueryRow(ctx, getDraftCharacterUpdate, id)
	var i ActionResultCharacterUpdate
	err := row.Scan(
		&i.ID,
		&i.ActionResultID,
		&i.CharacterID,
		&i.ModuleType,
		&i.FieldName,
		&i.FieldValue,
		&i.FieldType,
		&i.Operation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftCharacterUpdates = `-- name: GetDraftCharacterUpdates :many
SELECT id, action_result_id, character_id, module_type, field_name, field_value, field_type, operation, created_at, updated_at FROM action_result_character_updates
WHERE action_result_id = $1
ORDER BY module_type, field_name
`

// Get all draft character updates for an action result
func (q *Queries) GetDraftCharacterUpdates(ctx context.Context, actionResultID int32) ([]ActionResultCharacterUpdate, error) {
	rows, err := q.db.Query(ctx, getDraftCharacterUpdates, actionResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionResultCharacterUpdate
	for rows.Next() {
		var i ActionResultCharacterUpdate
		if err := rows.Scan(
			&i.ID,
			&i.ActionResultID,
			&i.CharacterID,
			&i.ModuleType,
			&i.FieldName,
			&i.FieldValue,
			&i.FieldType,
			&i.Operation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftUpdateCount = `-- name: GetDraftUpdateCount :one
SELECT COUNT(*) FROM action_result_character_updates
WHERE action_result_id = $1
`

// Count the number of draft updates for an action result
func (q *Queries) GetDraftUpdateCount(ctx context.Context, actionResultID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getDraftUpdateCount, actionResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const publishDraftCharacterUpdates = `-- name: PublishDraftCharacterUpdates :exec
WITH draft_updates AS (
    SELECT
        character_id,
        module_type,
        field_name,
        field_value,
        field_type
    FROM action_result_character_updates
    WHERE action_result_id = $1 AND operation = 'upsert'
)
INSERT INTO character_data (character_id, module_type, field_name, field_value, field_type)
SELECT character_id, module_type, field_name, field_value, field_type
FROM draft_updates
ON CONFLICT (character_id, module_type, field_name)
DO UPDATE SET
    field_value = EXCLUDED.field_value,
    field_type = EXCLUDED.field_type,
    updated_at = NOW()
`

// Copy draft updates to character_data table (only upsert operations)
func (q *Queries) PublishDraftCharacterUpdates(ctx context.Context, actionResultID int32) error {
	_, err := q.db.Exec(ctx, publishDraftCharacterUpdates, actionResultID)
	return err
}

const updateDraftCharacterUpdate = `-- name: UpdateDraftCharacterUpdate :one
UPDATE action_result_character_updates
SET
    field_value = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, action_result_id, character_id, module_type, field_name, field_value, field_type, operation, created_at, updated_at
`

type UpdateDraftCharacterUpdateParams struct {
	ID         int32       `json:"id"`
	FieldValue pgtype.Text `json:"field_value"`
}

// Update the field value of an existing draft
func (q *Queries) UpdateDraftCharacterUpdate(ctx context.Context, arg UpdateDraftCharacterUpdateParams) (ActionResultCharacterUpdate, error) {
	row := q.db.QueryRow(ctx, updateDraftCharacterUpdate, arg.ID, arg.FieldValue)
	var i ActionResultCharacterUpdate
	err := row.Scan(
		&i.ID,
		&i.ActionResultID,
		&i.CharacterID,
		&i.ModuleType,
		&i.FieldName,
		&i.FieldValue,
		&i.FieldType,
		&i.Operation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
