// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversationUnreadCount = `-- name: GetConversationUnreadCount :one
SELECT COUNT(*) as unread_count
FROM private_messages pm
WHERE
  pm.conversation_id = $1
  AND pm.created_at > COALESCE(
    (SELECT last_read_at FROM conversation_reads WHERE user_id = $2 AND conversation_id = $1),
    '1970-01-01'::timestamptz
  )
`

type GetConversationUnreadCountParams struct {
	ConversationID int32 `json:"conversation_id"`
	UserID         int32 `json:"user_id"`
}

// Count unread messages in a conversation for a user
func (q *Queries) GetConversationUnreadCount(ctx context.Context, arg GetConversationUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationUnreadCount, arg.ConversationID, arg.UserID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const getFirstUnreadMessageID = `-- name: GetFirstUnreadMessageID :one
SELECT pm.id
FROM private_messages pm
WHERE
  pm.conversation_id = $1
  AND pm.created_at > COALESCE(
    (SELECT last_read_at FROM conversation_reads WHERE user_id = $2 AND conversation_id = $1),
    '1970-01-01'::timestamptz
  )
ORDER BY pm.created_at ASC, pm.id ASC
LIMIT 1
`

type GetFirstUnreadMessageIDParams struct {
	ConversationID int32 `json:"conversation_id"`
	UserID         int32 `json:"user_id"`
}

// Get the ID of the first unread message in a conversation for a user
func (q *Queries) GetFirstUnreadMessageID(ctx context.Context, arg GetFirstUnreadMessageIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFirstUnreadMessageID, arg.ConversationID, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserConversationRead = `-- name: GetUserConversationRead :one
SELECT id, user_id, conversation_id, last_read_message_id, last_read_at, created_at, updated_at
FROM conversation_reads
WHERE user_id = $1 AND conversation_id = $2
`

type GetUserConversationReadParams struct {
	UserID         int32 `json:"user_id"`
	ConversationID int32 `json:"conversation_id"`
}

// Get the read tracking information for a specific user and conversation
func (q *Queries) GetUserConversationRead(ctx context.Context, arg GetUserConversationReadParams) (ConversationRead, error) {
	row := q.db.QueryRow(ctx, getUserConversationRead, arg.UserID, arg.ConversationID)
	var i ConversationRead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationRead = `-- name: UpsertConversationRead :one
INSERT INTO conversation_reads (user_id, conversation_id, last_read_message_id, last_read_at)
VALUES (
  $1,
  $2,
  $3,
  COALESCE(
    (SELECT created_at FROM private_messages WHERE id = $3),
    NOW()
  )
)
ON CONFLICT (user_id, conversation_id)
DO UPDATE SET
  last_read_message_id = EXCLUDED.last_read_message_id,
  last_read_at = COALESCE(
    (SELECT created_at FROM private_messages WHERE id = EXCLUDED.last_read_message_id),
    NOW()
  ),
  updated_at = NOW()
RETURNING id, user_id, conversation_id, last_read_message_id, last_read_at, created_at, updated_at
`

type UpsertConversationReadParams struct {
	UserID            int32       `json:"user_id"`
	ConversationID    int32       `json:"conversation_id"`
	LastReadMessageID pgtype.Int4 `json:"last_read_message_id"`
}

// Update or insert read tracking for a conversation
// Uses the message's created_at timestamp to accurately track read position
func (q *Queries) UpsertConversationRead(ctx context.Context, arg UpsertConversationReadParams) (ConversationRead, error) {
	row := q.db.QueryRow(ctx, upsertConversationRead, arg.UserID, arg.ConversationID, arg.LastReadMessageID)
	var i ConversationRead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
