// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deadlines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeadline = `-- name: CreateDeadline :one
INSERT INTO game_deadlines (game_id, title, description, deadline, created_by_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, title, description, deadline, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateDeadlineParams struct {
	GameID          int32              `json:"game_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Deadline        pgtype.Timestamptz `json:"deadline"`
	CreatedByUserID int32              `json:"created_by_user_id"`
}

func (q *Queries) CreateDeadline(ctx context.Context, arg CreateDeadlineParams) (GameDeadline, error) {
	row := q.db.QueryRow(ctx, createDeadline,
		arg.GameID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.CreatedByUserID,
	)
	var i GameDeadline
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDeadline = `-- name: DeleteDeadline :exec
UPDATE game_deadlines
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDeadline(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDeadline, id)
	return err
}

const getAllGameDeadlines = `-- name: GetAllGameDeadlines :many
SELECT
    'deadline' as deadline_type,
    gd.id as source_id,
    gd.title as title,
    gd.description as description,
    gd.deadline as deadline,
    gd.game_id,
    NULL::INTEGER as phase_id,
    NULL::INTEGER as poll_id,
    false as is_system_deadline
FROM game_deadlines gd
WHERE gd.game_id = $1
  AND gd.deleted_at IS NULL
  AND ($2 = true OR gd.deadline > NOW())

UNION ALL

SELECT
    'phase' as deadline_type,
    gp.id as source_id,
    gp.title as title,
    CONCAT(gp.phase_type, ' Phase ', gp.phase_number) as description,
    gp.deadline as deadline,
    gp.game_id,
    gp.id as phase_id,
    NULL::INTEGER as poll_id,
    true as is_system_deadline
FROM game_phases gp
WHERE gp.game_id = $1
  AND gp.is_active = true
  AND gp.deadline IS NOT NULL
  AND ($2 = true OR gp.deadline > NOW())

UNION ALL

SELECT
    'poll' as deadline_type,
    crp.id as source_id,
    crp.question as title,
    COALESCE(crp.description, 'Poll voting deadline') as description,
    crp.deadline as deadline,
    crp.game_id,
    crp.phase_id,
    crp.id as poll_id,
    false as is_system_deadline
FROM common_room_polls crp
WHERE crp.game_id = $1
  AND crp.is_deleted = false
  AND crp.deadline IS NOT NULL
  AND ($2 = true OR crp.deadline > NOW())

ORDER BY deadline ASC
`

type GetAllGameDeadlinesParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
}

type GetAllGameDeadlinesRow struct {
	DeadlineType     string             `json:"deadline_type"`
	SourceID         int32              `json:"source_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Deadline         pgtype.Timestamptz `json:"deadline"`
	GameID           int32              `json:"game_id"`
	PhaseID          pgtype.Int4        `json:"phase_id"`
	PollID           pgtype.Int4        `json:"poll_id"`
	IsSystemDeadline bool               `json:"is_system_deadline"`
}

// Aggregate ALL deadlines for a game: arbitrary, phase, and poll deadlines
func (q *Queries) GetAllGameDeadlines(ctx context.Context, arg GetAllGameDeadlinesParams) ([]GetAllGameDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, getAllGameDeadlines, arg.GameID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGameDeadlinesRow
	for rows.Next() {
		var i GetAllGameDeadlinesRow
		if err := rows.Scan(
			&i.DeadlineType,
			&i.SourceID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.GameID,
			&i.PhaseID,
			&i.PollID,
			&i.IsSystemDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeadline = `-- name: GetDeadline :one
SELECT id, game_id, title, description, deadline, created_by_user_id, created_at, updated_at, deleted_at FROM game_deadlines
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeadline(ctx context.Context, id int32) (GameDeadline, error) {
	row := q.db.QueryRow(ctx, getDeadline, id)
	var i GameDeadline
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpiredDeadlines = `-- name: GetExpiredDeadlines :many
SELECT id, game_id, title, description, deadline, created_by_user_id, created_at, updated_at, deleted_at FROM game_deadlines
WHERE deleted_at IS NULL
  AND deadline <= NOW()
ORDER BY deadline DESC
`

// For cleanup jobs or notifications
func (q *Queries) GetExpiredDeadlines(ctx context.Context) ([]GameDeadline, error) {
	rows, err := q.db.Query(ctx, getExpiredDeadlines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameDeadline
	for rows.Next() {
		var i GameDeadline
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDeadlines = `-- name: GetGameDeadlines :many
SELECT id, game_id, title, description, deadline, created_by_user_id, created_at, updated_at, deleted_at FROM game_deadlines
WHERE game_id = $1
  AND deleted_at IS NULL
  AND (
    -- Include expired deadlines if requested
    $2 = true OR deadline > NOW()
  )
ORDER BY deadline ASC
`

type GetGameDeadlinesParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) GetGameDeadlines(ctx context.Context, arg GetGameDeadlinesParams) ([]GameDeadline, error) {
	rows, err := q.db.Query(ctx, getGameDeadlines, arg.GameID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameDeadline
	for rows.Next() {
		var i GameDeadline
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingDeadlinesForUser = `-- name: GetUpcomingDeadlinesForUser :many
SELECT
    gd.id, gd.game_id, gd.title, gd.description, gd.deadline, gd.created_by_user_id, gd.created_at, gd.updated_at, gd.deleted_at,
    g.title as game_title,
    g.id as game_id
FROM game_deadlines gd
JOIN games g ON gd.game_id = g.id
LEFT JOIN game_participants gp ON g.id = gp.game_id AND gp.user_id = $1
WHERE gd.deleted_at IS NULL
  AND gd.deadline > NOW()
  AND (
    g.gm_user_id = $1  -- User is GM
    OR (gp.user_id = $1 AND gp.status = 'active')  -- User is participant
  )
ORDER BY gd.deadline ASC
LIMIT $2
`

type GetUpcomingDeadlinesForUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetUpcomingDeadlinesForUserRow struct {
	ID              int32              `json:"id"`
	GameID          int32              `json:"game_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Deadline        pgtype.Timestamptz `json:"deadline"`
	CreatedByUserID int32              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	GameTitle       string             `json:"game_title"`
	GameID_2        int32              `json:"game_id_2"`
}

// Get upcoming deadlines across all games user participates in
func (q *Queries) GetUpcomingDeadlinesForUser(ctx context.Context, arg GetUpcomingDeadlinesForUserParams) ([]GetUpcomingDeadlinesForUserRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDeadlinesForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingDeadlinesForUserRow
	for rows.Next() {
		var i GetUpcomingDeadlinesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GameTitle,
			&i.GameID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeadline = `-- name: UpdateDeadline :one
UPDATE game_deadlines
SET title = $2, description = $3, deadline = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, game_id, title, description, deadline, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateDeadlineParams struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) UpdateDeadline(ctx context.Context, arg UpdateDeadlineParams) (GameDeadline, error) {
	row := q.db.QueryRow(ctx, updateDeadline,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Deadline,
	)
	var i GameDeadline
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
