// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discord.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserDiscordAccount = `-- name: DeleteUserDiscordAccount :exec
DELETE FROM user_discord_accounts
WHERE user_id = $1
`

// Remove a user's Discord account link
func (q *Queries) DeleteUserDiscordAccount(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserDiscordAccount, userID)
	return err
}

const getUserDiscordAccount = `-- name: GetUserDiscordAccount :one
SELECT id, user_id, discord_user_id, discord_username, access_token, refresh_token, token_expires_at, created_at, updated_at
FROM user_discord_accounts
WHERE user_id = $1
`

// Get a user's Discord account by user ID
func (q *Queries) GetUserDiscordAccount(ctx context.Context, userID int32) (UserDiscordAccount, error) {
	row := q.db.QueryRow(ctx, getUserDiscordAccount, userID)
	var i UserDiscordAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordUserID,
		&i.DiscordUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserDiscordAccount = `-- name: UpsertUserDiscordAccount :one
INSERT INTO user_discord_accounts (
  user_id,
  discord_user_id,
  discord_username,
  access_token,
  refresh_token,
  token_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id)
DO UPDATE SET
  discord_user_id  = EXCLUDED.discord_user_id,
  discord_username = EXCLUDED.discord_username,
  access_token     = EXCLUDED.access_token,
  refresh_token    = EXCLUDED.refresh_token,
  token_expires_at = EXCLUDED.token_expires_at,
  updated_at       = NOW()
RETURNING id, user_id, discord_user_id, discord_username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type UpsertUserDiscordAccountParams struct {
	UserID          int32              `json:"user_id"`
	DiscordUserID   string             `json:"discord_user_id"`
	DiscordUsername string             `json:"discord_username"`
	AccessToken     string             `json:"access_token"`
	RefreshToken    pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
}

// Insert or update a user's Discord account
func (q *Queries) UpsertUserDiscordAccount(ctx context.Context, arg UpsertUserDiscordAccountParams) (UserDiscordAccount, error) {
	row := q.db.QueryRow(ctx, upsertUserDiscordAccount,
		arg.UserID,
		arg.DiscordUserID,
		arg.DiscordUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i UserDiscordAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordUserID,
		&i.DiscordUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
