// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fingerprint_bans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFingerprintBan = `-- name: CreateFingerprintBan :one
INSERT INTO fingerprint_bans (
    fingerprint, created_by, reason
) VALUES (
    $1, $2, $3
)
RETURNING id, fingerprint, created_by, created_at, reason
`

type CreateFingerprintBanParams struct {
	Fingerprint string      `json:"fingerprint"`
	CreatedBy   int32       `json:"created_by"`
	Reason      pgtype.Text `json:"reason"`
}

func (q *Queries) CreateFingerprintBan(ctx context.Context, arg CreateFingerprintBanParams) (FingerprintBan, error) {
	row := q.db.QueryRow(ctx, createFingerprintBan, arg.Fingerprint, arg.CreatedBy, arg.Reason)
	var i FingerprintBan
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Reason,
	)
	return i, err
}

const deleteFingerprintBan = `-- name: DeleteFingerprintBan :exec
DELETE FROM fingerprint_bans
WHERE id = $1
`

func (q *Queries) DeleteFingerprintBan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFingerprintBan, id)
	return err
}

const isFingerprintBanned = `-- name: IsFingerprintBanned :one
SELECT EXISTS(
    SELECT 1 FROM fingerprint_bans
    WHERE fingerprint = $1
) AS banned
`

func (q *Queries) IsFingerprintBanned(ctx context.Context, fingerprint string) (bool, error) {
	row := q.db.QueryRow(ctx, isFingerprintBanned, fingerprint)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listFingerprintBans = `-- name: ListFingerprintBans :many
SELECT id, fingerprint, created_by, created_at, reason FROM fingerprint_bans
ORDER BY created_at DESC
`

func (q *Queries) ListFingerprintBans(ctx context.Context) ([]FingerprintBan, error) {
	rows, err := q.db.Query(ctx, listFingerprintBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FingerprintBan
	for rows.Next() {
		var i FingerprintBan
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
