// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO game_logs (
    game_id, type, message
) VALUES (
    $1, $2, $3
) RETURNING id, game_id, type, message, created_at
`

type CreateLogParams struct {
	GameID  int32       `json:"game_id"`
	Type    string      `json:"type"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (GameLog, error) {
	row := q.db.QueryRow(ctx, createLog, arg.GameID, arg.Type, arg.Message)
	var i GameLog
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getGameLogs = `-- name: GetGameLogs :many
SELECT
    id, game_id, type, message, created_at
FROM game_logs
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetGameLogs(ctx context.Context, gameID int32) ([]GameLog, error) {
	rows, err := q.db.Query(ctx, getGameLogs, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameLog
	for rows.Next() {
		var i GameLog
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
