// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_loot_tables.sql

package db

import (
	"context"
)

const createLootTable = `-- name: CreateLootTable :one
INSERT INTO game_loot_tables (
    game_id, name
) VALUES (
    $1, $2
) RETURNING id, game_id, name, created_at
`

type CreateLootTableParams struct {
	GameID int32  `json:"game_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateLootTable(ctx context.Context, arg CreateLootTableParams) (GameLootTable, error) {
	row := q.db.QueryRow(ctx, createLootTable, arg.GameID, arg.Name)
	var i GameLootTable
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLootTable = `-- name: DeleteLootTable :exec
DELETE FROM game_loot_tables WHERE id = $1
`

func (q *Queries) DeleteLootTable(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLootTable, id)
	return err
}

const getLootTables = `-- name: GetLootTables :many
SELECT
    id, game_id, name, created_at
FROM game_loot_tables
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetLootTables(ctx context.Context, gameID int32) ([]GameLootTable, error) {
	rows, err := q.db.Query(ctx, getLootTables, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameLootTable
	for rows.Next() {
		var i GameLootTable
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
