// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ip_bans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIPBan = `-- name: CreateIPBan :one
INSERT INTO ip_bans (
    ip_address, created_by, reason, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, ip_address, created_by, created_at, reason, expires_at
`

type CreateIPBanParams struct {
	IpAddress string             `json:"ip_address"`
	CreatedBy int32              `json:"created_by"`
	Reason    pgtype.Text        `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIPBan(ctx context.Context, arg CreateIPBanParams) (IpBan, error) {
	row := q.db.QueryRow(ctx, createIPBan,
		arg.IpAddress,
		arg.CreatedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i IpBan
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Reason,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIPBans = `-- name: DeleteExpiredIPBans :exec
DELETE FROM ip_bans
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredIPBans(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIPBans)
	return err
}

const deleteIPBan = `-- name: DeleteIPBan :exec
DELETE FROM ip_bans
WHERE id = $1
`

func (q *Queries) DeleteIPBan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIPBan, id)
	return err
}

const getIPBanByAddress = `-- name: GetIPBanByAddress :one
SELECT id, ip_address, created_by, created_at, reason, expires_at FROM ip_bans
WHERE ip_address = $1
LIMIT 1
`

func (q *Queries) GetIPBanByAddress(ctx context.Context, ipAddress string) (IpBan, error) {
	row := q.db.QueryRow(ctx, getIPBanByAddress, ipAddress)
	var i IpBan
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Reason,
		&i.ExpiresAt,
	)
	return i, err
}

const isIPBanned = `-- name: IsIPBanned :one
SELECT EXISTS(
    SELECT 1 FROM ip_bans
    WHERE ip_address = $1
      AND (expires_at IS NULL OR expires_at > NOW())
) AS banned
`

func (q *Queries) IsIPBanned(ctx context.Context, ipAddress string) (bool, error) {
	row := q.db.QueryRow(ctx, isIPBanned, ipAddress)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listIPBans = `-- name: ListIPBans :many
SELECT id, ip_address, created_by, created_at, reason, expires_at FROM ip_bans
WHERE expires_at IS NULL OR expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListIPBans(ctx context.Context) ([]IpBan, error) {
	rows, err := q.db.Query(ctx, listIPBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpBan
	for rows.Next() {
		var i IpBan
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Reason,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
