// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentRegistrationAttemptsByEmail = `-- name: CountRecentRegistrationAttemptsByEmail :one
SELECT COUNT(*) FROM registration_attempts
WHERE email = $1
  AND created_at > $2
`

type CountRecentRegistrationAttemptsByEmailParams struct {
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentRegistrationAttemptsByEmail(ctx context.Context, arg CountRecentRegistrationAttemptsByEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegistrationAttemptsByEmail, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegistrationAttemptsByIP = `-- name: CountRecentRegistrationAttemptsByIP :one
SELECT COUNT(*) FROM registration_attempts
WHERE ip_address = $1
  AND created_at > $2
`

type CountRecentRegistrationAttemptsByIPParams struct {
	IpAddress string             `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentRegistrationAttemptsByIP(ctx context.Context, arg CountRecentRegistrationAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegistrationAttemptsByIP, arg.IpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistrationAttempt = `-- name: CreateRegistrationAttempt :one
INSERT INTO registration_attempts (
    email, username, ip_address, user_agent, captcha_passed, honeypot_triggered, blocked_reason, successful
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, email, username, ip_address, user_agent, honeypot_triggered, captcha_passed, blocked_reason, successful, created_at
`

type CreateRegistrationAttemptParams struct {
	Email             string      `json:"email"`
	Username          string      `json:"username"`
	IpAddress         string      `json:"ip_address"`
	UserAgent         pgtype.Text `json:"user_agent"`
	CaptchaPassed     bool        `json:"captcha_passed"`
	HoneypotTriggered bool        `json:"honeypot_triggered"`
	BlockedReason     pgtype.Text `json:"blocked_reason"`
	Successful        bool        `json:"successful"`
}

func (q *Queries) CreateRegistrationAttempt(ctx context.Context, arg CreateRegistrationAttemptParams) (RegistrationAttempt, error) {
	row := q.db.QueryRow(ctx, createRegistrationAttempt,
		arg.Email,
		arg.Username,
		arg.IpAddress,
		arg.UserAgent,
		arg.CaptchaPassed,
		arg.HoneypotTriggered,
		arg.BlockedReason,
		arg.Successful,
	)
	var i RegistrationAttempt
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.IpAddress,
		&i.UserAgent,
		&i.HoneypotTriggered,
		&i.CaptchaPassed,
		&i.BlockedReason,
		&i.Successful,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldRegistrationAttempts = `-- name: DeleteOldRegistrationAttempts :exec
DELETE FROM registration_attempts
WHERE created_at < $1
`

func (q *Queries) DeleteOldRegistrationAttempts(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRegistrationAttempts, createdAt)
	return err
}

const getRecentSuccessfulRegistrationByIP = `-- name: GetRecentSuccessfulRegistrationByIP :one
SELECT id, email, username, ip_address, user_agent, honeypot_triggered, captcha_passed, blocked_reason, successful, created_at FROM registration_attempts
WHERE ip_address = $1
  AND successful = TRUE
  AND created_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentSuccessfulRegistrationByIPParams struct {
	IpAddress string             `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentSuccessfulRegistrationByIP(ctx context.Context, arg GetRecentSuccessfulRegistrationByIPParams) (RegistrationAttempt, error) {
	row := q.db.QueryRow(ctx, getRecentSuccessfulRegistrationByIP, arg.IpAddress, arg.CreatedAt)
	var i RegistrationAttempt
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.IpAddress,
		&i.UserAgent,
		&i.HoneypotTriggered,
		&i.CaptchaPassed,
		&i.BlockedReason,
		&i.Successful,
		&i.CreatedAt,
	)
	return i, err
}
