// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, data, expires, ip_address, user_agent, fingerprint
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, data, expires, ip_address, user_agent, fingerprint, created_at, last_seen_at
`

type CreateSessionParams struct {
	UserID      int32              `json:"user_id"`
	Data        string             `json:"data"`
	Expires     pgtype.Timestamptz `json:"expires"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Data,
		arg.Expires,
		arg.IpAddress,
		arg.UserAgent,
		arg.Fingerprint,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
		&i.IpAddress,
		&i.UserAgent,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE data = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, data string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, data)
	return err
}

const deleteSessionsByFingerprint = `-- name: DeleteSessionsByFingerprint :exec
DELETE FROM sessions
WHERE fingerprint = $1
`

func (q *Queries) DeleteSessionsByFingerprint(ctx context.Context, fingerprint pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSessionsByFingerprint, fingerprint)
	return err
}

const deleteSessionsByIP = `-- name: DeleteSessionsByIP :exec
DELETE FROM sessions
WHERE ip_address = $1
`

func (q *Queries) DeleteSessionsByIP(ctx context.Context, ipAddress pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteSessionsByIP, ipAddress)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

// Invalidate all sessions for a user (used when banning)
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, data, expires, ip_address, user_agent, fingerprint, created_at, last_seen_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
		&i.IpAddress,
		&i.UserAgent,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, data, expires, ip_address, user_agent, fingerprint, created_at, last_seen_at FROM sessions
WHERE data = $1 LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, data string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, data)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
		&i.IpAddress,
		&i.UserAgent,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSessionsByUser = `-- name: GetSessionsByUser :many
SELECT id, user_id, data, expires, ip_address, user_agent, fingerprint, created_at, last_seen_at FROM sessions
WHERE user_id = $1 AND expires > NOW()
`

func (q *Queries) GetSessionsByUser(ctx context.Context, userID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Data,
			&i.Expires,
			&i.IpAddress,
			&i.UserAgent,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionsWithDetails = `-- name: GetUserSessionsWithDetails :many
SELECT id, ip_address, user_agent, fingerprint, created_at, last_seen_at, expires
FROM sessions
WHERE user_id = $1 AND expires > NOW()
ORDER BY last_seen_at DESC
`

type GetUserSessionsWithDetailsRow struct {
	ID          int32              `json:"id"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	Expires     pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) GetUserSessionsWithDetails(ctx context.Context, userID int32) ([]GetUserSessionsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessionsWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsWithDetailsRow
	for rows.Next() {
		var i GetUserSessionsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :exec
UPDATE sessions
SET ip_address = $2, user_agent = $3, fingerprint = $4
WHERE id = $1
`

type UpdateSessionMetadataParams struct {
	ID          int32       `json:"id"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) error {
	_, err := q.db.Exec(ctx, updateSessionMetadata,
		arg.ID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Fingerprint,
	)
	return err
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE sessions
SET data = $2
WHERE id = $1
`

type UpdateSessionTokenParams struct {
	ID   int32  `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionToken, arg.ID, arg.Data)
	return err
}
