// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePendingUser = `-- name: ApprovePendingUser :exec
UPDATE users
SET pending_approval = FALSE,
    pending_approval_since = NULL
WHERE id = $1
`

func (q *Queries) ApprovePendingUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, approvePendingUser, id)
	return err
}

const banUser = `-- name: BanUser :exec

UPDATE users
SET is_banned = TRUE,
    banned_at = NOW(),
    banned_by_user_id = $2
WHERE id = $1
`

type BanUserParams struct {
	ID             int32       `json:"id"`
	BannedByUserID pgtype.Int4 `json:"banned_by_user_id"`
}

// User banning queries
func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BannedByUserID)
	return err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
WHERE (
    $1::text = '' OR username ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%'
)
`

func (q *Queries) CountAllUsers(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one

INSERT INTO email_verification_tokens (
    user_id, email, token, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, token, email, created_at, expires_at, used_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    int32              `json:"user_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Email Verification Tokens
func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (
    user_id, token, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token, created_at, expires_at, used_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Password Reset Tokens
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password, email
) VALUES (
             $1, $2, $3
         )
RETURNING id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
		&i.EmailVerified,
		&i.EmailChangePending,
		&i.PasswordChangedAt,
		&i.UsernameChangedAt,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.PendingApproval,
		&i.PendingApprovalSince,
	)
	return i, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE FROM email_verification_tokens
WHERE expires_at < NOW()
  OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < NOW()
  OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getDeletedUser = `-- name: GetDeletedUser :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE id = $1
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getDeletedUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
		&i.EmailVerified,
		&i.EmailChangePending,
		&i.PasswordChangedAt,
		&i.UsernameChangedAt,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.PendingApproval,
		&i.PendingApprovalSince,
	)
	return i, err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token, email, created_at, expires_at, used_at FROM email_verification_tokens
WHERE token = $1
  AND used_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, created_at, expires_at, used_at FROM password_reset_tokens
WHERE token = $1
  AND used_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
		&i.EmailVerified,
		&i.EmailChangePending,
		&i.PasswordChangedAt,
		&i.UsernameChangedAt,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.PendingApproval,
		&i.PendingApprovalSince,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE LOWER(email) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
		&i.EmailVerified,
		&i.EmailChangePending,
		&i.PasswordChangedAt,
		&i.UsernameChangedAt,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.PendingApproval,
		&i.PendingApprovalSince,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE LOWER(username) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
		&i.EmailVerified,
		&i.EmailChangePending,
		&i.PasswordChangedAt,
		&i.UsernameChangedAt,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.PendingApproval,
		&i.PendingApprovalSince,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, email, created_at
FROM users
WHERE is_admin = TRUE
ORDER BY created_at ASC
`

type ListAdminsRow struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE (
    $1::text = '' OR username ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%'
)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Timezone,
			&i.EmailNotifications,
			&i.HighContrast,
			&i.IsBanned,
			&i.BannedAt,
			&i.BannedByUserID,
			&i.EmailVerified,
			&i.EmailChangePending,
			&i.PasswordChangedAt,
			&i.UsernameChangedAt,
			&i.DeletedAt,
			&i.DeletionScheduledFor,
			&i.PendingApproval,
			&i.PendingApprovalSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBannedUsers = `-- name: ListBannedUsers :many
SELECT u.id, u.username, u.email, u.banned_at, u.banned_by_user_id, u.created_at,
       admin.username as banned_by_username
FROM users u
LEFT JOIN users admin ON u.banned_by_user_id = admin.id
WHERE u.is_banned = TRUE
ORDER BY u.banned_at DESC
`

type ListBannedUsersRow struct {
	ID               int32            `json:"id"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	BannedAt         pgtype.Timestamp `json:"banned_at"`
	BannedByUserID   pgtype.Int4      `json:"banned_by_user_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	BannedByUsername pgtype.Text      `json:"banned_by_username"`
}

func (q *Queries) ListBannedUsers(ctx context.Context) ([]ListBannedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBannedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBannedUsersRow
	for rows.Next() {
		var i ListBannedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.BannedAt,
			&i.BannedByUserID,
			&i.CreatedAt,
			&i.BannedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalUsers = `-- name: ListPendingApprovalUsers :many
SELECT id, username, email, password, is_admin, created_at, display_name, bio, avatar_url, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id, email_verified, email_change_pending, password_changed_at, username_changed_at, deleted_at, deletion_scheduled_for, pending_approval, pending_approval_since FROM users
WHERE pending_approval = TRUE
ORDER BY created_at ASC
`

func (q *Queries) ListPendingApprovalUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Timezone,
			&i.EmailNotifications,
			&i.HighContrast,
			&i.IsBanned,
			&i.BannedAt,
			&i.BannedByUserID,
			&i.EmailVerified,
			&i.EmailChangePending,
			&i.PasswordChangedAt,
			&i.UsernameChangedAt,
			&i.DeletedAt,
			&i.DeletionScheduledFor,
			&i.PendingApproval,
			&i.PendingApprovalSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified = TRUE
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const permanentlyDeleteUser = `-- name: PermanentlyDeleteUser :exec
DELETE FROM users
WHERE id = $1
  AND deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PermanentlyDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, permanentlyDeleteUser, id)
	return err
}

const restoreDeletedUser = `-- name: RestoreDeletedUser :exec
UPDATE users
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreDeletedUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, restoreDeletedUser, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many

SELECT id, username, email, created_at
FROM users
WHERE username ILIKE '%' || $1 || '%'
  AND is_banned = FALSE
ORDER BY username
LIMIT 20
`

type SearchUsersRow struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// User search queries
func (q *Queries) SearchUsers(ctx context.Context, dollar_1 pgtype.Text) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailChangePending = `-- name: SetEmailChangePending :exec
UPDATE users
SET email_change_pending = $2
WHERE id = $1
`

type SetEmailChangePendingParams struct {
	ID                 int32       `json:"id"`
	EmailChangePending pgtype.Text `json:"email_change_pending"`
}

func (q *Queries) SetEmailChangePending(ctx context.Context, arg SetEmailChangePendingParams) error {
	_, err := q.db.Exec(ctx, setEmailChangePending, arg.ID, arg.EmailChangePending)
	return err
}

const setPendingApproval = `-- name: SetPendingApproval :exec
UPDATE users
SET pending_approval = TRUE,
    pending_approval_since = NOW()
WHERE id = $1
`

func (q *Queries) SetPendingApproval(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setPendingApproval, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec

UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

// Account Deletion (Soft Delete with 30-day recovery)
func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users
SET is_banned = FALSE,
    banned_at = NULL,
    banned_by_user_id = NULL
WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
set username = $2,
    password = $3,
    email = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	return err
}

const updateUserAdminStatus = `-- name: UpdateUserAdminStatus :exec

UPDATE users
SET is_admin = $2
WHERE id = $1
`

type UpdateUserAdminStatusParams struct {
	ID      int32       `json:"id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

// Admin management queries
func (q *Queries) UpdateUserAdminStatus(ctx context.Context, arg UpdateUserAdminStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserAdminStatus, arg.ID, arg.IsAdmin)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $2,
    email_verified = TRUE,
    email_change_pending = NULL
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec

UPDATE users
SET password = $2,
    password_changed_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int32  `json:"id"`
	Password string `json:"password"`
}

// Password Management
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :exec
UPDATE users
SET username = $2,
    username_changed_at = NOW()
WHERE id = $1
`

type UpdateUserUsernameParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUserUsername, arg.ID, arg.Username)
	return err
}
