// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package db

import (
	"context"
)

const deleteUserPreferences = `-- name: DeleteUserPreferences :exec
DELETE FROM user_preferences
WHERE user_id = $1
`

// Delete all preferences for a user (cascade handles this on user deletion, but keeping for completeness)
func (q *Queries) DeleteUserPreferences(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserPreferences, userID)
	return err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT id, user_id, preferences, created_at, updated_at
FROM user_preferences
WHERE user_id = $1
`

// Get user preferences by user ID
func (q *Queries) GetUserPreferences(ctx context.Context, userID int32) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferenceField = `-- name: UpdateUserPreferenceField :one
UPDATE user_preferences
SET
  preferences = jsonb_set(preferences, $2::text[], $3::jsonb, true),
  updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, preferences, created_at, updated_at
`

type UpdateUserPreferenceFieldParams struct {
	UserID  int32    `json:"user_id"`
	Column2 []string `json:"column_2"`
	Column3 []byte   `json:"column_3"`
}

// Update a single preference field without replacing entire JSON
// $2 is the JSON path as text array, e.g. '{theme}' for top-level or '{notification_settings,email_enabled}' for nested
func (q *Queries) UpdateUserPreferenceField(ctx context.Context, arg UpdateUserPreferenceFieldParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPreferenceField, arg.UserID, arg.Column2, arg.Column3)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_id, preferences)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
  preferences = EXCLUDED.preferences,
  updated_at = NOW()
RETURNING id, user_id, preferences, created_at, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID      int32  `json:"user_id"`
	Preferences []byte `json:"preferences"`
}

// Create or update user preferences
func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences, arg.UserID, arg.Preferences)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
