// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserProfileGames = `-- name: CountUserProfileGames :one
SELECT COUNT(DISTINCT g.id)
FROM games g
LEFT JOIN game_participants gp ON gp.game_id = g.id AND gp.user_id = $1 AND gp.removed_at IS NULL AND (gp.role != 'audience' OR gp.is_former_player = TRUE)
WHERE g.gm_user_id = $1 OR (gp.user_id = $1 AND gp.removed_at IS NULL AND (gp.role != 'audience' OR gp.is_former_player = TRUE))
`

// CountUserProfileGames counts total games a user has participated in (for profile page)
func (q *Queries) CountUserProfileGames(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProfileGames, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserAvatar = `-- name: DeleteUserAvatar :exec
UPDATE users
SET avatar_url = NULL
WHERE id = $1
`

// DeleteUserAvatar removes a user's avatar by setting avatar_url to NULL
func (q *Queries) DeleteUserAvatar(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUserAvatar, id)
	return err
}

const getUserGames = `-- name: GetUserGames :many
SELECT
    g.id as game_id,
    g.title,
    g.state,
    g.is_anonymous,
    g.gm_user_id,
    gm_user.username as gm_username,
    COALESCE(gp.role, 'gm') as user_role,
    g.created_at,
    g.updated_at,
    -- Character details (NULL for anonymous games)
    CASE
        WHEN g.is_anonymous THEN NULL
        ELSE c.id
    END as character_id,
    CASE
        WHEN g.is_anonymous THEN NULL
        ELSE c.name
    END as character_name,
    CASE
        WHEN g.is_anonymous THEN NULL
        ELSE c.avatar_url
    END as character_avatar_url,
    CASE
        WHEN g.is_anonymous THEN NULL
        ELSE c.character_type
    END as character_type
FROM games g
JOIN users gm_user ON g.gm_user_id = gm_user.id
LEFT JOIN game_participants gp ON gp.game_id = g.id AND gp.user_id = $1 AND gp.removed_at IS NULL AND (gp.role != 'audience' OR gp.is_former_player = TRUE)
LEFT JOIN characters c ON c.game_id = g.id AND c.user_id = $1
WHERE g.gm_user_id = $1 OR (gp.user_id = $1 AND gp.removed_at IS NULL AND (gp.role != 'audience' OR gp.is_former_player = TRUE))
ORDER BY
    CASE g.state
        WHEN 'in_progress' THEN 1
        WHEN 'character_creation' THEN 2
        WHEN 'recruitment' THEN 3
        WHEN 'completed' THEN 4
        WHEN 'cancelled' THEN 5
        WHEN 'paused' THEN 6
        ELSE 7
    END,
    g.updated_at DESC
LIMIT $2 OFFSET $3
`

type GetUserGamesParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserGamesRow struct {
	GameID             int32              `json:"game_id"`
	Title              string             `json:"title"`
	State              pgtype.Text        `json:"state"`
	IsAnonymous        bool               `json:"is_anonymous"`
	GmUserID           int32              `json:"gm_user_id"`
	GmUsername         string             `json:"gm_username"`
	UserRole           string             `json:"user_role"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CharacterID        interface{}        `json:"character_id"`
	CharacterName      interface{}        `json:"character_name"`
	CharacterAvatarUrl interface{}        `json:"character_avatar_url"`
	CharacterType      interface{}        `json:"character_type"`
}

// GetUserGames retrieves all games a user has participated in
// with privacy filtering for anonymous games (character details hidden)
// Includes games where user is GM, participant, or both
// Supports pagination with limit and offset
func (q *Queries) GetUserGames(ctx context.Context, arg GetUserGamesParams) ([]GetUserGamesRow, error) {
	rows, err := q.db.Query(ctx, getUserGames, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGamesRow
	for rows.Next() {
		var i GetUserGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.Title,
			&i.State,
			&i.IsAnonymous,
			&i.GmUserID,
			&i.GmUsername,
			&i.UserRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CharacterID,
			&i.CharacterName,
			&i.CharacterAvatarUrl,
			&i.CharacterType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one

SELECT
    id,
    username,
    email,
    display_name,
    bio,
    avatar_url,
    created_at,
    timezone,
    is_admin
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserProfileRow struct {
	ID          int32            `json:"id"`
	Username    string           `json:"username"`
	Email       string           `json:"email"`
	DisplayName pgtype.Text      `json:"display_name"`
	Bio         pgtype.Text      `json:"bio"`
	AvatarUrl   pgtype.Text      `json:"avatar_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Timezone    pgtype.Text      `json:"timezone"`
	IsAdmin     pgtype.Bool      `json:"is_admin"`
}

// User Profile Queries
// These queries support the user profile system, allowing users to view and edit their profiles
// and view game history with privacy filtering for anonymous games.
// GetUserProfile retrieves a user's profile information
func (q *Queries) GetUserProfile(ctx context.Context, id int32) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Timezone,
		&i.IsAdmin,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $2
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        int32       `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// UpdateUserAvatar updates a user's avatar URL
func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    bio = COALESCE($3, bio)
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID          int32       `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
}

// UpdateUserProfile updates a user's display name and bio
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Bio)
	return err
}
